#+title: dino

My library for Godot addons that haven't earned their wings just yet,
and a godot game that tries to use them all.

'Dino' sort of comes from 'demo', but it provides a punch of personality.

Also it gives us a cast of characters to pull from.

These are intended to speed up prototyping and game-jam workflows, but should
also be useful in longer-running projects.

* ideas/works-in-progress
** beehive
For working with state machines, behavior trees, maybe GOAP
** trolley
For handling controls inputs and remapping.
** navi
Basic menus, pausing, and credits, plus a scene loader for navigating between
them all.
** dj
For sounds and music management, such as background music that is maintained
across scene transitions.
** tyle
Tools scripts and ui to improve on Godot's TileSet UI gap.
Includes some basic auto-tiles to speed up prototyping.
** thanks
A simple Credits scene that reads from a .txt file
* this project is also a consumer of [[github:russmatney/bb-godot]]
bb-godot provides command-line helpers:

- auto-exporting from aseprite
- building a local web build
- deploying to s3
- installing addons from github

Maybe that tool should be absorbed into here?
