@tool
extends DJSoundMap

enum {
	jump,
	fall,
	heavy_fall,
	coin,
	swordswing,
	soldierhit,
	soldierdead,
	collectpowerup,
	showjumbotron,
	climbstart,
	playerheal,
	playerhurt,
	enemyhurt,
	bosswarp,
	boss_shoot,
	boss_swoop,
	destroyed_block,
	candleout,
	candlelit,
	enemylaugh,
	bosslaugh,
	nodamageclang,
	}

###########################################################################
# sounds

var sounds = {
	jump:
	[
			preload("res://src/hatbot/sounds/jump1.sfxr"),
		],
	fall:
	[
			preload("res://src/hatbot/sounds/fall1.sfxr"),
			preload("res://src/hatbot/sounds/fall2.sfxr"),
			preload("res://src/hatbot/sounds/fall3.sfxr"),
		],
	heavy_fall:
	[
			preload("res://src/hatbot/sounds/heavyfall1.sfxr"),
			preload("res://src/hatbot/sounds/heavyfall2.sfxr"),
		],
	coin:
	[
			preload("res://src/hatbot/sounds/coin1.sfxr"),
			preload("res://src/hatbot/sounds/coin2.sfxr"),
			preload("res://src/hatbot/sounds/coin3.sfxr"),
		],
	swordswing:
	[
			preload("res://src/hatbot/sounds/swordswing1.sfxr"),
			preload("res://src/hatbot/sounds/swordswing2.sfxr"),
			preload("res://src/hatbot/sounds/swordswing3.sfxr"),
		],
	soldierhit:
	[
			preload("res://src/hatbot/sounds/soldierhit.sfxr"),
			preload("res://src/hatbot/sounds/soldierhit1.sfxr"),
			preload("res://src/hatbot/sounds/soldierhit2.sfxr"),
		],
	soldierdead:
	[
			preload("res://src/hatbot/sounds/soldierdead1.sfxr"),
			preload("res://src/hatbot/sounds/soldierdead2.sfxr"),
			preload("res://src/hatbot/sounds/soldierdead3.sfxr"),
		],
	collectpowerup:
	[
			preload("res://assets/sounds/collectpowerup1.sfxr"),
			preload("res://assets/sounds/collectpowerup2.sfxr"),
		],
	showjumbotron:
	[
			preload("res://assets/sounds/showjumbotron1.sfxr"),
			preload("res://assets/sounds/showjumbotron2.sfxr"),
			preload("res://assets/sounds/showjumbotron3.sfxr"),
		],
	climbstart:
	[
			preload("res://assets/sounds/climbstart1.sfxr"),
			preload("res://assets/sounds/climbstart2.sfxr"),
		],
	playerheal:
	[
			preload("res://assets/sounds/playerheal1.sfxr"),
			preload("res://assets/sounds/playerheal2.sfxr"),
		],
	playerhurt:
	[
			preload("res://assets/sounds/player_hurt1.sfxr"),
			preload("res://assets/sounds/player_hurt2.sfxr"),
			preload("res://assets/sounds/player_hurt3.sfxr"),
		],
	enemyhurt:
	[
			preload("res://assets/sounds/enemy_hurt1.sfxr"),
			preload("res://assets/sounds/enemy_hurt2.sfxr"),
			preload("res://assets/sounds/enemy_hurt3.sfxr"),
		],
	bosswarp:
	[
			preload("res://assets/sounds/bosswarp1.sfxr"),
			preload("res://assets/sounds/bosswarp2.sfxr"),
		],
	boss_shoot:
	[
			preload("res://assets/sounds/boss_shoot1.sfxr"),
			preload("res://assets/sounds/boss_shoot2.sfxr"),
			preload("res://assets/sounds/boss_shoot3.sfxr"),
		],
	boss_swoop:
	[
			preload("res://assets/sounds/boss_swoop1.sfxr"),
			preload("res://assets/sounds/boss_swoop2.sfxr"),
			preload("res://assets/sounds/boss_swoop3.sfxr"),
		],
	destroyed_block:
	[
			preload("res://assets/sounds/destroyedblock1.sfxr"),
			preload("res://assets/sounds/destroyedblock2.sfxr"),
			preload("res://assets/sounds/destroyedblock3.sfxr"),
		],
	candleout:
	[
			preload("res://assets/sounds/candleout1.sfxr"),
			preload("res://assets/sounds/candleout2.sfxr"),
		],
	candlelit:
	[
			preload("res://assets/sounds/candlelit1.sfxr"),
			preload("res://assets/sounds/candlelit2.sfxr"),
		],
	enemylaugh:
	[
			preload("res://assets/sounds/enemylaugh1.sfxr"),
			preload("res://assets/sounds/enemylaugh2.sfxr"),
			preload("res://assets/sounds/enemylaugh3.sfxr"),
		],
	bosslaugh:
	[
			preload("res://assets/sounds/bosslaugh1.sfxr"),
			preload("res://assets/sounds/bosslaugh2.sfxr"),
			preload("res://assets/sounds/bosslaugh3.sfxr"),
		],
	nodamageclang:
	[
			preload("res://assets/sounds/nodamageclang.sfxr"),
			preload("res://assets/sounds/nodamageclang2.sfxr"),
			preload("res://assets/sounds/nodamageclang3.sfxr"),
		],
}
