@tool
extends DJSoundMap

enum {
	jump,
	fall,
	heavy_fall,
	coin,
	swordswing,
	soldierhit,
	soldierdead,
	collectpowerup,
	showjumbotron,
	climbstart,
	playerheal,
	playerhurt,
	bosswarp,
	boss_shoot,
	boss_swoop,
	destroyed_block,
	}

###########################################################################
# sounds

var sounds = {
	jump:
	[
			preload("res://src/mvania19/sounds/jump1.sfxr"),
		],
	fall:
	[
			preload("res://src/mvania19/sounds/fall1.sfxr"),
			preload("res://src/mvania19/sounds/fall2.sfxr"),
			preload("res://src/mvania19/sounds/fall3.sfxr"),
		],
	heavy_fall:
	[
			preload("res://src/mvania19/sounds/heavyfall1.sfxr"),
			preload("res://src/mvania19/sounds/heavyfall2.sfxr"),
		],
	coin:
	[
			preload("res://src/mvania19/sounds/coin1.sfxr"),
			preload("res://src/mvania19/sounds/coin2.sfxr"),
			preload("res://src/mvania19/sounds/coin3.sfxr"),
		],
	swordswing:
	[
			preload("res://src/mvania19/sounds/swordswing1.sfxr"),
			preload("res://src/mvania19/sounds/swordswing2.sfxr"),
			preload("res://src/mvania19/sounds/swordswing3.sfxr"),
		],
	soldierhit:
	[
			preload("res://src/mvania19/sounds/soldierhit.sfxr"),
			preload("res://src/mvania19/sounds/soldierhit1.sfxr"),
			preload("res://src/mvania19/sounds/soldierhit2.sfxr"),
		],
	soldierdead:
	[
			preload("res://src/mvania19/sounds/soldierdead1.sfxr"),
			preload("res://src/mvania19/sounds/soldierdead2.sfxr"),
			preload("res://src/mvania19/sounds/soldierdead3.sfxr"),
		],
	collectpowerup:
	[
			preload("res://assets/sounds/collectpowerup1.sfxr"),
			preload("res://assets/sounds/collectpowerup2.sfxr"),
		],
	showjumbotron:
	[
			preload("res://assets/sounds/showjumbotron1.sfxr"),
			preload("res://assets/sounds/showjumbotron2.sfxr"),
			preload("res://assets/sounds/showjumbotron3.sfxr"),
		],
	climbstart:
	[
			preload("res://assets/sounds/climbstart1.sfxr"),
			preload("res://assets/sounds/climbstart2.sfxr"),
		],
	playerheal:
	[
			preload("res://assets/sounds/playerheal1.sfxr"),
			preload("res://assets/sounds/playerheal2.sfxr"),
		],
	playerhurt:
	[
			preload("res://assets/sounds/player_hurt1.sfxr"),
			preload("res://assets/sounds/player_hurt2.sfxr"),
			preload("res://assets/sounds/player_hurt3.sfxr"),
		],
	bosswarp:
	[
			preload("res://assets/sounds/bosswarp1.sfxr"),
			preload("res://assets/sounds/bosswarp2.sfxr"),
		],
	boss_shoot:
	[
			preload("res://assets/sounds/boss_shoot1.sfxr"),
			preload("res://assets/sounds/boss_shoot2.sfxr"),
			preload("res://assets/sounds/boss_shoot3.sfxr"),
		],
	boss_swoop:
	[
			preload("res://assets/sounds/boss_swoop1.sfxr"),
			preload("res://assets/sounds/boss_swoop2.sfxr"),
			preload("res://assets/sounds/boss_swoop3.sfxr"),
		],
	destroyed_block:
	[
			preload("res://assets/sounds/destroyedblock1.sfxr"),
			preload("res://assets/sounds/destroyedblock2.sfxr"),
			preload("res://assets/sounds/destroyedblock3.sfxr"),
		],
}
