#+title: Dino Games

Dino was originally intended as a monorepo full of independent games - a
jumpstarter for doing game jams. I was experimenting! Along the way I wasn't
sure if it would make sense to persue a more serious game alongside the others,
or if the addons would be consumable from another repo.

At this point I want to shake things up - I'm trying to hone in on some reusable
controllers and game designs, and see if I can refactor all the pieces to fit
together.

Anyway, for posterity, here's the old games documention!

* Void Spike:
Play the web version here: [[https://russmatney.itch.io/spike][russmatney.itch.io/spike]]

A submission for the GMTK Game Jam 2023
* Shirt:
Play the web version here: [[https://russmatney.itch.io/shirt][russmatney.itch.io/shirt]]

A submission for the [[https://itch.io/jam/godot-wild-jam-58][Godot Wild Jam #58]]
* Mountain:
A work-in-progress.
* Super Elevator Level:
Play the downloadable version here: [[https://russmatney.itch.io/super-elevator-level][russmatney.itch.io/super-elevator-level]]

Or the webversion: [[https://russmatney.itch.io/super-elevator-level-web][russmatney.itch.io/super-elevator-level-web]]

Submitted to the [[https://itch.io/jam/go-godot-jam-4][Go Godot Jam 4]]
* Herd: A sheep bullet hell
No separate itch page and build yet - but playable in Dino's main deploy:
[[https://russmatney.itch.io/dino][russmatney.itch.io/dino]].

I worked on this for the Bullet Hell Jam 2023, but didn't end up submitting -
it's still very prototypey.
* Mvania 19: HatBot
A submission for [[https://itch.io/jam/metroidvania-month-19][Metroidvania Month-long Jam 19]].

Play the downloadable version here: [[https://russmatney.itch.io/mvania19][russmatney.itch.io/mvania19]]

Or the webversion: [[https://russmatney.itch.io/mvania19][russmatney.itch.io/mvania19-web]]
* Tower
A Jetpack-fueled mess of propulsion in some generated tilemaps.

I built much of Reptile (a dino addon) while working on this game.

Play the deployed version here: [[https://russmatney.itch.io/tower][russmatney.itch.io/tower]]
* Cozy Gunner
A juicy gunner.

Play the deployed version here: [[https://russmatney.itch.io/gunner][russmatney.itch.io/gunner]]
* Harvey
An overcooked-like farming game. Submission for the Ludum Dare 52 (Theme: Harvest).

Play the deployed version here: [[https://russmatney.itch.io/harvey][russmatney.itch.io/harvey]]
* Pluggs
A fun character - just a bucket of plugs.

Play the deployed version here: [[https://russmatney.itch.io/pluggs][russmatney.itch.io/pluggs]]
* Ghost House
Play the deployed version here: [[https://russmatney.itch.io/ghosts][russmatney.itch.io/ghosts]]

A small something created for the [[https://itch.io/jam/godot-wild-jam-52][Godot Wild Jam #52]].
* Snake
A rough prototype for [[https://itch.io/jam/gdb-juice-jam-ii][Juice Jam 2]].

Play the deployed version here: [[https://russmatney.itch.io/snake][russmatney.itch.io/snake]]
* Runner
Play the deployed version here: [[https://russmatney.itch.io/runner][russmatney.itch.io/runner]]

A catch-the-leaf inspired running game.

The core of the logic is the Runner.gd script, which handles adding and removing
rooms while the player moves across them until they are all complete.
* Dungeon Crawler
Play the deployed version here: [[https://russmatney.itch.io/dungeon-crawler][russmatney.itch.io/dungeon-crawler]]

This was a chance to implement keys and door logic, and a basic boss state
machine. The map is one giant scene, and the tiles use auto-tiling, which should
make it simple to doodle a few more levels.
