# Do not modify! Auto-generated file.
class_name MetroTravelPointIds


const HATBOTLEVELZEROTOLANDINGSITE = "213"
const HATBOTLEVELZEROTOTHEKINGDOM = "214"
const HATBOTLANDINGSITETOZERO = "215"
const HATBOTLANDINGSITETOKINGDOMBACK = "216"
const HATBOTLANDINGSITETOSIMULATION = "217"
const HATBOTLANDINGSITETOVOLCANO = "218"
const HATBOTSIMULATIONTOLANDINGSITE = "219"
const HATBOTSIMULATIONTOKINGDOM = "220"
const HATBOTKINGDOMTOSIMULATION = "221"
const HATBOTKINGDOMTOLANDINGSITE = "222"
const HATBOTKINGDOMTOLEVELZERO = "223"
const HATBOTVOLCANOTOLANDINGSITE = "224"
