name: Godot Export and Itch Deploy
on: [ push ]

env:
  GODOT_VERSION: 4.1.1

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    environment: Godot Dev Env
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Issue 120
        run: |
          mkdir -p /github/home/.config/godot
          cp /root/.config/godot/editor_settings-4.tres /github/home/.config/godot/
      - name: Sanity check
        run: ls /root/.local/share/godot/templates
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Initial Godot import
        shell: bash
        run: |
          godot --quiet --editor --headless -s addons/core/initial_import.gd
          godot --editor --headless --quit || exit 0
      - name: Windows Build
        # TODO remove forced exit 0 here (export without errors!)
        run: |
          mkdir -v -p dist/dino-windows
          godot --headless -v --export-release dino-windows dist/dino-windows/dino.exe
      - name: Sanity check
        run: |
          ls -alh dist/
          ls -alh dist/dino-windows
      - name: Deploy windows to itch.io
        run: BUTLER_API_KEY=${{secrets.BUTLER_API_KEY}} butler push dist/dino-windows russmatney/dino:windows


  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    environment: Godot Dev Env
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Issue 120
        run: |
          mkdir -p /github/home/.config/godot
          cp /root/.config/godot/editor_settings-4.tres /github/home/.config/godot/
      - name: Sanity check
        run: ls /root/.local/share/godot/templates
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Initial Godot import
        shell: bash
        run: |
          godot --quiet --editor --headless -s addons/core/initial_import.gd
          godot --editor --headless --quit || exit 0
      - name: Linux Build
        # TODO remove forced exit 0 here (export without errors!)
        run: |
          mkdir -v -p dist/dino-linux
          godot --headless -v --export-release dino-linux dist/dino-linux/dino.x86_64
      - name: Sanity check
        run: |
          ls -alh dist/
          ls -alh dist/dino-linux
      - name: Deploy linux to itch.io
        run: BUTLER_API_KEY=${{secrets.BUTLER_API_KEY}} butler push dist/dino-linux russmatney/dino:linux-universal

  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    environment: Godot Dev Env
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Issue 120
        run: |
          mkdir -p /github/home/.config/godot
          cp /root/.config/godot/editor_settings-4.tres /github/home/.config/godot/
      - name: Sanity check
        run: ls /root/.local/share/godot/templates
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Initial Godot import
        shell: bash
        run: |
          godot --quiet --editor --headless -s addons/core/initial_import.gd
          godot --editor --headless --quit || exit 0
      - name: Web Build
        # TODO remove forced exit 0 here (export without errors!)
        run: |
          mkdir -v -p dist/dino-web
          godot --headless -v --export-release dino-web dist/dino-web/index.html
      - name: Sanity check
        run: |
          ls -alh dist/
          ls -alh dist/dino-web
      - name: Deploy web build to itch.io (dino)
        run: BUTLER_API_KEY=${{secrets.BUTLER_API_KEY}} butler push dist/dino-web russmatney/dino:html5
      - name: Deploy web build to itch.io (dino-web)
        run: BUTLER_API_KEY=${{secrets.BUTLER_API_KEY}} butler push dist/dino-web russmatney/dino-web:html5

  export-mac:
    name: Mac Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    environment: Godot Dev Env
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Issue 120
        run: |
          mkdir -p /github/home/.config/godot
          cp /root/.config/godot/editor_settings-4.tres /github/home/.config/godot/
      - name: Sanity check
        run: ls /root/.local/share/godot/templates
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Initial Godot import
        shell: bash
        run: |
          godot --quiet --editor --headless -s addons/core/initial_import.gd
          godot --editor --headless --quit || exit 0
      - name: Mac Build
        # TODO remove forced exit 0 here (export without errors!)
        run: |
          mkdir -v -p dist/dino-macos
          godot --headless -v --export-release dino-macos dist/dino-macos/dino.dmg
      - name: Sanity check
        run: |
          ls -alh dist/
          ls -alh dist/dino-macos
      - name: Deploy mac build to itch.io
        run: BUTLER_API_KEY=${{secrets.BUTLER_API_KEY}} butler push dist/dino-macos russmatney/dino:macos-universal
