name: GUT Tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Godot Dev Env
    steps:
    - uses: actions/checkout@v2

    - name: Cache Godot files
      id: cache-godot
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/share/godot/**
          /usr/local/bin/godot
          ~/.config/godot/**
        key: ${{ runner.os }}-godot-${{ vars.GODOT_VERSION }}

    - name: Download and config Godot Engine headless linux server
      if: steps.cache-godot.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget -q https://downloads.tuxfamily.org/godotengine/${{ vars.GODOT_VERSION }}/Godot_v${{ vars.GODOT_VERSION }}-stable_linux.x86_64.zip
        mkdir ~/.cache
        mkdir -p ~/.config/godot
        unzip Godot_v${{ vars.GODOT_VERSION }}-stable_linux.x86_64.zip
        mv Godot_v${{ vars.GODOT_VERSION }}-stable_linux.x86_64 /usr/local/bin/godot
        godot --quiet --editor --headless -s addons/core/initial_import.gd
        godot --editor --headless --quit

    - name: Run tests
      shell: bash
      run: godot --headless --path . -d -s addons/gut/gut_cmdln.gd -gexit
