name: Unit Tests
run-name: ${{ github.head_ref || github.ref_name }}-dino-unit-tests

on:
  # pull_request:
  workflow_dispatch:
  push:

concurrency:
  group: dino-unit-tests-${{ github.event.number }}

jobs:
  unit-test:
    name: "GDUnit Tests"
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 10 # The overall timeout
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        godot-version: ['4.2.1']
        godot-status: ['stable']

    steps:
      # checkout your repository
      - uses: actions/checkout@v4
        with:
          lfs: true
      # run unit tests
      - uses: MikeSchulze/gdUnit4-action@v1.0.5
        with:
          godot-version: ${{ matrix.godot-version }}
          godot-status: ${{ matrix.godot-status }}
          paths: |
            res://test/
          timeout: 5
          upload-report: false
